### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by COD3BREAK3R** [pushqrdx/vscode-inline-html#17]
I tried this extension inside a javascript file and Emmet did not work or anything.

**Comment by pushqrdx** [comment]
@COD3BREAK3R thanks for reporting, can you please report 

1. vscode version
2. Other (similar functionality) extensions that you have installed, if any
3. Snippet of the code you're trying to get the extension to work on

I'd really appreciate these info as it will definitely help fixing the issue.

**Comment by pushqrdx** [comment]
will close this issue as i haven't received useful info on reproduction, feel free to reopen. Thanks
