### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by dan80flo** [pushqrdx/vscode-inline-html#18]
- Issue Type: `Performance`
- Extension Name: `inline-html`
- Extension Version: `0.2.5`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.38.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\dam80\pushqrdx.inline-html-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by pushqrdx** [comment]
@dan80flo i know this is too much too late but if by any chance you still have this problem after the last update i pushed, please feel free to reopen
