### ISSUE TITLE
Comment-style tags broken

### ISSUE THREAD

**Issue by themerk** [pushqrdx/vscode-inline-html#24]
Unfortunately https://github.com/pushqrdx/vscode-inline-html/commit/81839d41e8f229a23b60eb41545027da13fce95f has broken the comment-style tags. I wish I knew enough regex to fix it!

Eg.
```
doSomething( /*html*/`<div class="test">test</div>`);
````

VSCode with v0.3.4:
![Screenshot - 24_01_2022 , 12_12_39 PM](https://user-images.githubusercontent.com/46369335/150711223-bc318a50-b6f2-43a0-91a0-fa23604cde8a.png)

VSCode with v0.3.3:
![Screenshot - 24_01_2022 , 12_13_50 PM](https://user-images.githubusercontent.com/46369335/150711296-03db86b3-acd0-42d2-be9e-ad10d930c9d2.png)

**Comment by pushqrdx** [comment]
@themerk urgh, ok i'll look into it today, sorry for that

**Comment by pushqrdx** [comment]
ok should be fixed now in 0.3.5
