### ISSUE TITLE
auto-completion of html code, including emmet, does not work

### ISSUE THREAD

**Issue by vadimmos** [pushqrdx/vscode-inline-html#33]
before pressing Enter
![example6](https://user-images.githubusercontent.com/14206443/189235976-e7b895b6-f7ee-4e25-8e8f-9160fe6d2d49.png)

after
![example7](https://user-images.githubusercontent.com/14206443/189236025-b499a6cc-3a70-41f0-a6b3-d79c89333eb2.png)

**Comment by pushqrdx** [comment]
@vadimmos some recent vscode update really messed things up, i need to track down what broke

**Comment by vadimmos** [comment]
pressing TAB doesn't change anything

**Comment by vadimmos** [comment]
this problem greatly slows down my work

**Comment by pushqrdx** [comment]
@vadimmos did you try the suggestions i made above? mainly `"emmet.triggerExpansionOnTab": true`

This problem appeared somewhere in one of the recent updates and i haven't been able to track down it's cause yet but using one of the workarounds above mitigates it for the time being

**Comment by vadimmos** [comment]
Thanks to this setting, it sometimes works. But I can't yet identify why sometimes it stops working even with this setting.

**Comment by pushqrdx** [comment]
@vadimmos alright finally figured out what happened, it appears like they somehow screwed the `emmet` extension but reverted it later [here](https://github.com/microsoft/vscode/commit/50140a53cc2088f478a5560683ccd354f2d5f431), if you install latest insider vscode build, `inline-html` is back working as expected
