### ISSUE TITLE
Support /* html */

### ISSUE THREAD

**Issue by daKmoR** [pushqrdx/vscode-inline-html#5]
It would be nice to support a syntax like
```js
return /* html */`
    <h2>foo</h2>
  `;
```
as well. 

Especially as eslint usually will complain if you write it like this `/*html*/`.

so you end up writing it like this :(
```js
// eslint-disable-next-line spaced-comment
return /*html*/`
    <h2>foo</h2>
  `;
```

**Comment by pushqrdx** [comment]
@daKmoR  this shouldn't be hard. I'll try to get to it this weekend. 
Regards!

**Comment by pushqrdx** [comment]
@daKmoR 😂 it's kinda funny but i just realized that i already included `/*html*/`while I was developing this extension so it should work. Have you actually tried to do 
```
/*html*/`

`
```

**Comment by daKmoR** [comment]
yes `/*html*/` works but it results in an eslint error... (as desribed above)

So my request is to adjust the regex a little to also allow `/* html */`

**Comment by daKmoR** [comment]
thhhxxx ❤️ 🤗 
that works perfectly 🎉
