### ISSUE TITLE
Context breaking in js if the string `html` is found

### ISSUE THREAD

**Issue by sergxerj** [pushqrdx/vscode-inline-html#52]
If I have code like:

```
let a = document.querySelector(`html`);
let b;
let c = document.querySelectorAll(`a`);
```

It seems to think that anything between the `html` and the `a` is in an html or css context, not sure of which, it gives hover tooltips like these:
![imagen](https://github.com/pushqrdx/vscode-inline-html/assets/72986199/10a2f3b4-701c-40e9-bbfa-e27815376162)
![imagen](https://github.com/pushqrdx/vscode-inline-html/assets/72986199/45342c96-fc4a-4542-bb2d-56b612bb7c78)

Things I have tried, these all make the problem go away:

* Disable/enable extension when it's the only one in the workspace (it's how I know it's this extension that causes it when enabled)
* Change the quotation marks in either `html` or `a` from backticks to single or double quotes
* Change the `html` string to something else that is not the literal `html` string (like `htm` or `tml` ).

**Comment by pushqrdx** [comment]
@sergxerj oh i see, i think i know what might be causing this

**Comment by pushqrdx** [comment]
@sergxerj v0.3.10 is up fixing this issue
