### ISSUE TITLE
Add support for styled components

### ISSUE THREAD

**Issue by brandonmcconnell** [pushqrdx/vscode-inline-html#54]
We often use this syntax:
```tsx
const StyledDiv = styled.div`
  color: red;
  font-size: 20px;
`;
```

But this is the syntax highlighting I see:
![](https://github.com/pushqrdx/vscode-inline-html/assets/5913254/d1716607-01cd-470f-a263-76a76e0c2376)

It would be great to support that syntax out of the box for CSS strings while retaining support for CSS intellisense and Emmet, etc.:
```tsx
styled.element`...`
```

**Comment by pushqrdx** [comment]
@brandonmcconnell sorry for the late reply but this feature already exists you have to use either `style` or `/*style*/` before the template literal, so
```js
/*style*/`
  color: red;
  font-size: 20px;
`
```
or
```js
style`
  color: red;
  font-size: 20px;
`
```

should work.
