### ISSUE TITLE
problem whith auto complete

### ISSUE THREAD

**Issue by drachehavoc** [pushqrdx/vscode-inline-html#9]
When I select a tag em press return:
![image](https://user-images.githubusercontent.com/1902294/51561275-eb551100-1e6d-11e9-9fba-51ea5876f03d.png)

the autocomplet return this
![image](https://user-images.githubusercontent.com/1902294/51561372-29eacb80-1e6e-11e9-9f4f-2ebd12825ef3.png)

and when I press ctr+z, it complets with this 
![image](https://user-images.githubusercontent.com/1902294/51561401-471f9a00-1e6e-11e9-952c-26b494bcd062.png)

Some times I select ```width``` and the autocomplete complets with ```windows```.

**Comment by pushqrdx** [comment]
@drachehavoc issue should be fixed with `v0.2.5`.

**Comment by pushqrdx** [comment]
@drachehavoc can you confirm fix so i can close this?

**Comment by drachehavoc** [comment]
Yes, it's fixed, thank you.

**Comment by pushqrdx** [comment]
no problem :)
